server:
  port: 12010

spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    consul: #Consul服务注册发现配置
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
    gateway:
      routes:
        - id: consul-client
          uri: lb://consul-client
          predicates:
            - Path=/user/**
##        我们⾃定义的路由 ID，保持唯⼀
#      - id: userservice
##        ⽬标服务名称
#        uri: lb://consul-client
##        路由条件所有的/user/地址都路由到 consul-client服务
#        predicates:
#          - Path=/user/**
##        路由重写 前端请求 /user/xxxx-> 后端接口 /user1/xxxx
##        filters:
##        - RewritePath=/user/(?<segment>.*), /user1/$\{segment}

